from typing import Literal, Optional
from pydantic import BaseModel, Field
import uuid


class MatchedColour(BaseModel):
    rgb: list[int]
    hsv: list[int]


class ParameterReading(BaseModel):
    name: str
    estimated_value: str
    unit: str
    risk_category: Literal["boiling_resistant_warning", "treatment_required", "low", "neutral"]
    matched_colour: Optional[MatchedColour] = None
    colour_distance: Optional[float] = None
    confidence: float
    message: str


class BoilingRiskFlag(BaseModel):
    parameter: str
    risk_level: Literal["warning", "critical"]
    reason: str


class CombinedBoilingRiskFlag(BaseModel):
    parameter: str
    risk_level: Literal["caution", "warning", "critical"]
    source_image_id: str
    reason: str


class ImageQuality(BaseModel):
    brightness: Literal["low", "acceptable", "high"]
    blur: Literal["low", "medium", "high"]
    lighting_warning: bool
    glare_warning: bool


class TDSResult(BaseModel):
    detected_text: str
    parsed_value: Optional[float]
    unit: str
    confidence: float
    risk_category: Literal["low", "caution", "warning", "high", "unknown"]
    status: Literal["processed", "manual_review_required"]
    message: str


class ImageResult(BaseModel):
    image_id: str
    kit_type: str
    declared_kit_type: Optional[str] = None
    kit_type_mismatch: bool = False
    processing_status: Literal["processed", "processed_with_warnings", "unable_to_process", "error"]
    parameters: list[ParameterReading] = Field(default_factory=list)
    tds_result: Optional[TDSResult] = None
    boiling_resistant_risk_flags: list[BoilingRiskFlag] = Field(default_factory=list)
    overall_confidence: float = 0.0
    image_quality: Optional[ImageQuality] = None
    warnings: list[str] = Field(default_factory=list)


class SubmissionResult(BaseModel):
    submission_id: str
    status: Literal["processed", "processed_with_warnings", "failed", "partial"]
    images_processed: int
    results: list[ImageResult]
    combined_boiling_resistant_risk_flags: list[CombinedBoilingRiskFlag] = Field(default_factory=list)
    final_module_warning: str = (
        "The image module does not decide whether water is safe to drink. "
        "Final guidance must be generated by the Water Quality Agent and Treatment Guidance Agent."
    )


# Legacy models kept for backward compatibility with single-image endpoints
class StripAnalysisResult(BaseModel):
    image_type: Literal["test_strip"] = "test_strip"
    kit_id: str
    parameters: list[ParameterReading]
    boiling_resistant_risk_flags: list[BoilingRiskFlag]
    overall_confidence: float
    image_quality: ImageQuality
    warnings: list[str]


class WaterAppearance(BaseModel):
    clarity: Literal["clear", "slightly_cloudy", "cloudy", "opaque"]
    colour: Literal["colourless", "slightly_yellow", "slightly_brown", "green", "other"]
    visible_particles: bool


class WaterSampleResult(BaseModel):
    image_type: Literal["water_sample"] = "water_sample"
    appearance: WaterAppearance
    overall_confidence: float
    warnings: list[str]
